name: devity_console
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.6.1
description: A new Flutter project.
dependencies:
  devity_sdk:
    path: ../devity_flutter_sdk
  awesome_snackbar_content: ^0.1.4
  bloc: ^9.0.0
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  multi_dropdown: ^3.0.1
  shared_preferences: ^2.2.2
  sizer: ^3.0.5
  url_strategy: ^0.3.0
  uuid: ^4.4.0
  device_preview_plus: ^2.2.6
  dotted_border: ^2.1.0
dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.12
  coverage: ^1.6.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.3.2
  mocktail: ^1.0.4
  pubspec_dependency_sorter: ^1.0.5
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env.development
    - .env.staging
    - .env.production
